### ISSUE TITLE
tcheck bug in PR #13

### ISSUE THREAD

**Issue by ulugbekna** [gasche/efftester#14]
Currently the `tcheck` fn in PR #13 is buggy: 

When checking that the type of PatternMatch is same as the type of bodies in pattern matching branches, the `tcheck` throws a type mismatch exception. 

Printing the types, however, shows that those types are same (when converted to a string at least).

Together with @gasche, we will use this issue to track the bug.

**Comment by gasche** [comment]
The plan is to use this issue for real-time bug hunting, so it's going to be more noisy than normal github issues.

@ulugbekna so the starting point is the reproduction steps you suggested: from your branch `add-option-support`, modify `ci_tests.ml` so that the test being run is `type_check_test`, and then run with the seed you gave

```
$ dune exec src/ci_tests.exe -- -v --colors -s 430633514
random seed: 430633514
generated error fail pass / total     time test name
[✗]    1    1    0    0 /  500     0.1s generated term type checks

=== Error ======================================================================

Test generated term type checks errored on (44 shrink steps):

Some (List.hd (let var5 = (<) 0 (let a = (match None with | Some v -> (fun j -> "")| None -> (fun z -> "")) in 0) in (match List.hd [] with | Some g -> (match None with | Some n -> []| None -> [])| None -> exit 0)))

exception Failure("tcheck: PatternMatch has a type mismatch")

================================================================================
failure (0 tests failed, 1 tests errored, ran 1 tests)
```

**Comment by ulugbekna** [comment]
That's what I did

**Comment by gasche** [comment]
Here are some thoughts when I see this report with the counterexample:

1. The shrinker could maybe shrink more. Is the unused `let var5 = ...` binding for example necessary to reproduce the bug? When we're done fixing this, I'm thinking of maybe re-introducing the bug to see how to improve the shrinker.

2. Having pretty-printing of the code examples would be nice. This is already planned.

3. The thing that is being printed, which is the OCaml rendering of the program, does not have all the informations that are necessary to understand what is going on: there is less information than the `term` value it was generated from. Indeed, we don't have the types and effect annotations, which could play an important role, and we don't know how the polymorphic things were instantiated (when you see `List.hd []` for example, at what type was that supposed to be?).

4. There is an error message, `"tcheck: PatternMatch has a type mismatch"`, which maybe can help. One thing we could do is go read that part of the code and see if something feels very wrong there.

**Comment by gasche** [comment]
Here are some things that I think we could try:

1. We could try to explore the failure at other seeds, in the hope of finding a smaller counter-example.

2. We could write a "raw printer" for the `term` structure that would give all the details about the content, so that we print the wrong value and try to understand what's going on from that, by running the `tcheck` code in our heads. (Sounds painful.)

3. We could marshal the `term` value to a file, and then load that back from an OCaml toplevel (sounds easy, but in theory there is a bit of setup to do that), and explore it in the toplevel.

4. We could go directly read the `tcheck` code around `PatternMatch`, and hope that the mistake will jump at us.

What would you like to try first?

**Comment by ulugbekna** [comment]
I did this in the first place to track down the bug: 
my `tcheck` case:
```ocaml
...
| PatternMatch (typ, _matched_trm, cases, eff) ->
    let has_type_mismatch typ1 typ2 = if types_compat typ1 typ2 then false else true in
    let has_type_mismatch_lst =
      List.exists
        (fun (_pat, body) ->
          if has_type_mismatch typ (imm_type body)
          then (
            Printf.printf
              "\npatmatch type: %s \nmatched_term: %s\nbody type: %s \nbody term: %s\n"
              (type_to_str typ)
              (term_to_ocaml _matched_trm)
              (type_to_str (imm_type body))
              (term_to_ocaml body);
            true)
          else false)
        cases
    in
...
```

**Comment by ulugbekna** [comment]
```
patmatch type: unit -> string 
matched_term: let (l: (int) list) = [75; ] in None
body type: unit -> string 
body term: let (j: bool -> unit) = (fun (d: bool) -> ()) in (fun (j: unit) -> "nggnha")
```

This is what I get. These are terms before they are shrunk.

Note how pat match type and body type are the same in printing but different when using `types_compat`.

**Comment by gasche** [comment]
Could it be that `types_compat` is wrong?

**Comment by gasche** [comment]
Note: `if foo then false else true` can be simplified as `not foo`.

**Comment by gasche** [comment]
The relevant line in `types_compat` is the following:

```ocaml
  | Fun (at, e, rt), Fun (at', e', rt') ->
    types_compat at' at && types_compat rt rt' && eff_leq e e'
```

notice the part on the effect. In your debug printing, could you pass `~effannot:true` to see the effect part of the two types?

**Comment by ulugbekna** [comment]
Yes, that's the problem.

**Comment by ulugbekna** [comment]
I was completely ignoring the effects part (maybe because it was a type-checking function or because I wrote `failwith "tcheck: PatternMatch has a type mismatch"`).

**Comment by ulugbekna** [comment]
Thank you for the help! I will try to see now why the effect generated is not what we want.

**Comment by ulugbekna** [comment]
Would it be correct to note that the type-checker should not be concerned with the effects? 
I could either create a version of types_compat that ignores effects or see how effect-checking can be useful to us.

**Comment by gasche** [comment]
Wait, I'm not sure I follow your reasoning.

**Comment by ulugbekna** [comment]
The types with effect annotations:
```
patmatch type: unit -true/false> string 
matched_term: let (l: (int) list) = [75; ] in None
body type: unit -false/false> string 
body term: let (j: bool -> unit) = (fun (d: bool) -> ()) in (fun (j: unit) -> "nggnha")
```

**Comment by gasche** [comment]
We see an error because the effect parts are not as the code expect them. You seem to be deducing from that that we should ignore the effect parts, so that this example would not fail anymore. But maybe it is important to check the effects and there really is a problem with the generator?

**Comment by ulugbekna** [comment]
> Wait, I'm not sure I follow your reasoning.

In pattern matching case of tcheck, I am checking that the pattern match type is same as that of branch bodies. However, the pattern match effect is the union of matched term _and_ bodies. So even if one of the bodies does not have an effect (- false/false), that is ok as long as some other body or matched term have ( - true / false).

**Comment by ulugbekna** [comment]
I think that 
```ocaml
match (print_endline "s" in None) with
| Some a -> print_endline "with effect" in "sdf"
| None -> "no effect"
``` 
should type check, which is not the case currently because the PatternMatch's effects is -true/false and the body of case None has effects : -false/false.

**Comment by gasche** [comment]
The `types_compat` code already uses the `eff_leq` operator, so that it should support having different effect bits in `typ` and `imm_type body`, but only in one direction of inclusion -- it is a bit strange that it is asymmetric in this way, while the name suggests it is symmetric. Could it be that you should pass the arguments to `type_compat` in the other order?

**Comment by ulugbekna** [comment]
Reversing the order does fix the problem.

**Comment by gasche** [comment]
@ulugbekna thanks! I'll let you fix the issue in the PR.

**Comment by ulugbekna** [comment]
Thank you a lot!
